<a href="https://colab.research.google.com/github/ashma19072006/C-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy stands for numerical python,ye python library h jo large amount of numerical data ko handle krne m madat krti h using array.


features-i>speed,ii>memory,iii>easy math operations,iv>used in ai,da,ds

In [ ]:
list =[1,2,3,4,5]
print(list)

import numpy as np
x=np.array([1,2,3,4,5])
print(x)#memory efficient

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
##1-d array
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10])
print(type(x))
print(x)
print(x.size)
print(x.shape)
print(x.ndim)
print(x[-6:-1])

<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10]
10
(10,)
1
[5 6 7 8 9]


In [ ]:
##2-d array
import numpy as np
x=np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
print(x)
print(x.size)
print(x.shape)
print(x.ndim)


[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
20
(2, 10)
2


In [ ]:
import numpy as np

r=np.ceil(29.6)
s=np.ceil(np.sum(np.sqrt([5,6,7])))
print(r)
print(s)

30.0
8.0


In [ ]:
import numpy as np
np.linspace(0,8,2)
a=np.array([1,2,3,4,5,6]).reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


##array creation

In [ ]:
import numpy as np

identity =np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##properties

In [ ]:
import numpy as np
arr =np.array([[1,2,3],[4,5,6]])
arr_3d=np.array([[[1,2],[3,4],[4,5]]])
print(arr.shape)#shape:-no. of rows and no. of columns
print(arr.size)#size:-no. of elements
print(arr.ndim)##ndim:-gives dimmension
print(arr.dtype)##dtype:-datatype
print(arr_3d)
print(arr_3d.ndim)


(2, 3)
6
2
int64
[[[1 2]
  [3 4]
  [4 5]]]
3


In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x.dtype)
str_arr = x.astype(str)
print(str_arr.dtype)
print(x+2)
print(x*2)

int64
<U21
[3 4 5 6 7]
[ 2  4  6  8 10]


In [ ]:
#aggregation function
import numpy as np
x=np.array([1,2,3,4,5])
print( "maximum",np.max(x))
print( "minimum",np.min(x))
print( "sum",np.sum(x))
print( "mean",np.mean(x))
print( "median",np.median(x))
print(np.std(x))
print(np.var(x))

maximum 5
minimum 1
sum 15
mean 3.0
median 3.0
1.4142135623730951
2.0


indexing and slicing


In [ ]:
#indexing and slicing for 1-d array

#indexing
import numpy as np
x =np.array([1,2,3,4,5])
print(x[1])
print(x[-1])#last element

#slicing:-extracting subset of data
#arr[start:stop:step]
print(x[0:2:1])
print(x[::-1])


2
5
[1 2]
[5 4 3 2 1]


In [ ]:
#indexing and slicing for 2-d array

#indexing
import numpy as np
x =np.array([[1,2,3],[2,3,4]])
print(x[1][2])
print(x[-1][-1])#last element

#slicing:-extracting subset of data
print(x[0:1])

4
4
[[1 2 3]]


In [ ]:
#fancy indexing
import numpy as np
x = np.array([10,20,30,40,50,60])
print(x[[0,2,4]])


#filtering data:-boolean masking
print(x[x>25])

[10 30 50]
[30 40 50 60]


##reshaping and manupulating

---
with the help of reshaping we can change rows and column of array ,no of elements will remain same.




In [ ]:
#we can only reshape the array when dimensions match,reshaping kabhi bhi copy create nhi krta it creates a view.

import numpy as np
x=np.array([1,2,3,4,5,6])
print(x.reshape(2,3))


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


flattening

In [ ]:
#multidimensional array -> 1-d array
#.ravel( )  ->original array will be effected in this case.
#.flatten() ->returns a copy

import numpy as np

arr =np.array([[20,30,40],[1,2,3]])
print(arr)
print(arr.ravel())
print(arr.flatten())


[[20 30 40]
 [ 1  2  3]]
[20 30 40  1  2  3]
[20 30 40  1  2  3]


##array modification


---

why?

In [ ]:
#np.insert(array,index,value,axis=None)
'''
for 1-d array:-
axis =none.
for 2-d array:-
axis =0(row)
axis=1(column)
'''
import numpy as np

arr=np.array([10,20,30,40,50])
new_arr=np.insert(arr,1,15,None)#axis agr nhi dalenge toh by default wo 0 rahega
print(arr)
print(new_arr)


[10 20 30 40 50]
[10 15 20 30 40 50]


In [ ]:
import numpy as np
arr =np.array([[1,2,3,5],[6,7,8,10]])
new=np.insert(arr,3,[4,9],1)
print(new)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#append
import numpy as np
arr =np.array([10,50,60])
new =np.insert(arr,1,[20,30,40])
print(new)

[10 20 30 40 50 60]


In [ ]:
#concatenate
'''
np.concatenate((arr1,arr2),axis=0)
axis 0>vertical stacking(row wise)
axis 1>horizonatal stacking(column wise)
'''

import numpy as np
arr1 =np.array([10,20,30])
arr2=np.array([40,50,60])
new =np.concatenate((arr1,arr2),axis=0)
print(new)


[10 20 30 40 50 60]


In [ ]:
#removing elements of 1-d array
#np.delete(array,index,axis=None)
import numpy as np
arr =np.array([10,20,30,40,50,60])
new =np.delete(arr,5)
print(new)


[10 20 30 40 50]


In [ ]:
#removing elements  of 2-d array
import numpy as np
arr =np.array([[1,2,3],[4,5,6]])
new =np.delete(arr,0,1)
print(new)


[[2 3]
 [5 6]]


In [ ]:
#stacking
#vstack() {row wise}
#hstack() {column wise}
import numpy as np
arr1 =np.array([10,20,30])
arr2=np.array([40,50,60])
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))



[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]


In [ ]:
#splitting:-1 array ko multiple subparts m devide krna
"""
np.split(array,no. of parts):-split in equal parts
np.hsplit()
np.vsplit()
"""
import numpy as np
arr1 =np.array([10,20,30,40])

print(np.split(arr1,2))


[array([10, 20]), array([30, 40])]


##Broadcasting

how numpy handkle arrays of different shapes?


i)matching dimensions:-


ii)Expanding single elements:-

iii)Incompatible shapes:-agar shapes different alag hote h to wo expand nhi ho skte ,numpy error dedega.

In [ ]:
#Expanding single elements


import numpy as np
arr =np.array([100,200,300])
result=arr*2
print(result)

[200 400 600]


In [ ]:
prices =[100,200,300]
discount =10
final_prices =[]

for price in prices:
  final_price =price -(price* discount/100)
  final_prices.append(final_price)

print(final_prices)

[90.0, 180.0, 270.0]


In [ ]:
#for loop se bachaega
#mathematical operation fast perform honge
import numpy as np
prices =np.array([100,200,300])
discount=10
final_prices =prices-(prices*discount/100)
print(final_prices)

[ 90. 180. 270.]


brodcasting in 2-d array

In [ ]:
#matching dimension wala tareeka

import numpy as np

matrix =np.array([[10,20,30],[40,50,60]])
vector =np.array([1,2,3])
result =matrix+vector
print(result)

[[11 22 33]
 [41 52 63]]


In [ ]:
#iii wala case jisme error ayega
import numpy as np
arr1 =np.array([[1,2,3],[4,5,6]])
arr2 =np.array([1,2,3,4])
result =arr1+arr2
print(result)

#reshape()

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

##vectorization

Vectorization means writing code that operates on whole arrays at once instead of using explicit Python loops.

In [ ]:
import numpy as np
arr =np.array([1,2,3,4])

mul =arr*3
print(mul)

[ 3  6  9 12]


##Handling misssing values

i)np.isnan(array):-detect missing values . nan(not a number)

In [ ]:
import numpy as np

arr =np.array([1,2,np.nan,4,np.nan])
print(np.isnan(arr))

##we can't compare nan values directly
##print(np.nan == np.nan)  wrong

[False False  True False  True]


ii)np.nan_to_num(array,nan =value) default =0

In [ ]:
import numpy as np

arr =np.array([1,2,np.nan,4,np.nan])
cleaned_arr =np.nan_to_num(arr,nan=1)
print(cleaned_arr)

[1. 2. 1. 4. 1.]


iii)np.isinf(array):-

In [ ]:
import numpy  as np

arr =np.array([1,2,np.inf,4,-np.inf])
print(np.isinf(arr))

[False False  True False  True]


In [ ]:
import numpy  as np

arr =np.array([1,2,np.inf,4,-np.inf])
print(np.isinf(arr))

cleaned_arr =np.nan_to_num(arr,posinf=100,neginf=-100)
print(cleaned_arr)

[False False  True False  True]
[   1.    2.  100.    4. -100.]


##Random number generation


rand,randn,randint

In [ ]:

#Random values in a given shape.
import numpy as np
np.random.rand(3,2)

array([[0.75857681, 0.77594897],
       [0.69817716, 0.40672777],
       [0.15319286, 0.99462362]])